---

- name: "Check existence of the service script"
  stat:
    path: "/etc/systemd/system/{{ jboss_jws_instance_name }}.service"
  register: service_script

- name: "Stop JBoss JWS"
  when: service_script.stat.exists
  ignore_errors: yes
  service:
    name: "{{ jboss_jws_instance_service_name }}"
    state: stopped
    enabled: no

- name: "Reload systemd"
  command: systemctl daemon-reload
  when: service_script.stat.exists

- name: "Remove all instance-specific files"
  file:
    name: "{{ item }}"
    state: absent
  become: yes
  with_items:
  - "{{ jboss_jws_instance_dir }}"
  - /etc/systemd/system/{{ jboss_jws_instance_service_name }}.service
