---

- name: "Step 5. Generate httpd.conf"
  template:
    src: httpd.conf.j2
    dest: "{{jws_apache.user_home }}/jws-3.0/httpd/conf/httpd.conf"
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
  become: true

- name: "Step 6. Generate ssl.conf"
  template:
    src: ssl.conf.j2
    dest: "{{jws_apache.user_home }}/jws-3.0/httpd/conf.d/ssl.conf"
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
  become: true

- name: "Step 7. Create mod_cluster configuration file"
  template:
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    src: mod_cluster.conf.j2
    dest: "{{jws_apache.user_home }}/jws-3.0/httpd/conf.d/mod_cluster.conf"
    mode: "0644"

- name: "STEP 8. Create the service directory"
  file:
    path: "{{jws_apache.user_home }}/jws-3.0/httpd/service"
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    state: directory
    mode: "0750"

- name: "STEP 9. Generate service systemd unit file"
  template:
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    src: jboss-jws-rhel.service.j2
    dest: "{{jws_apache.user_home }}/jws-3.0/httpd/service/{{ jboss_jws_instance_service_name }}.service"
    mode: "0750"

- name: "Step 10. Move configured installation into place"
  shell: "mv {{jws_apache.user_home }}/jws-3.0/httpd {{ jboss_jws_instance_dir }}"
  become_user: "{{ jws_apache.user }}"
  become: yes

- name: "Step 11. Generate JWS Apache systemd unit file"
  template:
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    src: jboss-jws-rhel.service.j2
    dest: "/etc/systemd/system/{{ jws_apache.service }}_{{ jboss_jws_instance_name }}.service"
    mode: "0755"
  register: systemd_service_file

- name: "Step 12. Reload systemd"
  when: systemd_service_file.changed == true
  command: systemctl daemon-reload
  notify: Restart JWS Apache