---

- name: "Step 5. Check existence of the JBoss JWS installation"
  stat:
    path: "{{ jws_httpd_zip_artifact_dl_dst  }}"
  register: jboss_jws_exists
  become: yes


#check for target extraction directory
- name: "Step 6. Ensures JWS user directory exists"
  file: path={{ item }} state=directory owner="{{ jws_apache.user }}" group="{{ jws_apache.group }}"
  become: yes
  with_items:
  - "{{ jws_apache.user_home }}"
  - "{{ jboss_jws_instance_dir }}"

- name: "Step 7. Extract JBoss Web Server HTTPD"
  unarchive:
    src: "{{ jws_httpd_zip_artifact_dl_dst }}"
    dest: "{{ jboss_jws_instance_dir }}"
    copy: false
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
  become: yes

- name: "Step 8. Updating owners"
  become: yes
  file: path={{ item }} owner={{ jws_apache.user }} group={{ jws_apache.group }}
  with_items:
    - "{{ jboss_jws_instance_dir }}"

