---

- name: "Step 9. Generate httpd.conf"
  template:
    src: httpd.conf.j2
    dest: "{{jws_apache.user_home }}/jws-3.0/httpd/conf/httpd.conf"
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
  become: true

- name: "Step 10. Remove ssl.conf"
  file:
    dest: "{{jws_apache.user_home }}/jws-3.0/httpd/conf.d/ssl.conf"
    state: absent
  become: true

- name: "Step 11. Create mod_cluster configuration file"
  template:
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    src: mod_cluster.conf.j2
    dest: "{{jws_apache.user_home }}/jws-3.0/httpd/conf.d/mod_cluster.conf"
    mode: "0644"

- name: "STEP 12. Create the service directory"
  file:
    path: "{{jws_apache.user_home }}/jws-3.0/httpd/service"
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    state: directory
    mode: "0750"

- name: "STEP 13. Generate service systemd unit file"
  template:
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    src: jboss-jws-rhel.service.j2
    dest: "{{jws_apache.user_home }}/jws-3.0/httpd/service/{{ jboss_jws_instance_service_name }}.service"
    mode: "0750"

- name: "Step 13b. set full path to httpd"
  lineinfile:
    regexp: "^HTTPD=.*"
    line: "HTTPD={{ jboss_jws_instance_dir }}/sbin/httpd"
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    dest: "{{jws_apache.user_home }}/jws-3.0/httpd/sbin/apachectl"
  become: yes

- name: "Step 14. Generate JWS Apache systemd unit file"
  template:
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    src: jboss-jws-rhel.service.j2
    dest: "/etc/systemd/system/{{ jws_apache.service }}_{{ jboss_jws_instance_name }}.service"
    mode: "0755"
  register: systemd_service_file
