---

- name: "Check existence of the service script"
  stat:
    path: "/etc/systemd/system/{{ jboss_jws_instance_name }}.service"

- name: "Stop JBoss JWS"
  ignore_errors: yes
  service:
    name: "{{ jboss_jws_instance_service_name }}"
    state: stopped
    enabled: no

- name: "Reload systemd"
  command: systemctl daemon-reload

- name: "Remove working dir"
  shell: rm -rf "{{ jboss_jws_instance_dir }}"
  become: yes


- name: "Remove all instance-specific files"
  file:
    name: "{{ item }}"
    state: absent
  become: yes
  with_items:
    - /etc/systemd/system/{{ jboss_jws_instance_service_name }}.service
