---

- name: "Step 9. Generate httpd.conf"
  template:
    src: httpd.conf.j2
    dest: "{{ jboss_jws_instance_dir }}/jws-3.0/httpd/conf/httpd.conf"
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
  become: true

- name: "Step 10. Remove ssl.conf"
  file:
    dest: "{{jboss_jws_instance_dir }}/jws-3.0/httpd/conf.d/ssl.conf"
    state: absent
  become: true

- name: "Step 11. Create mod_cluster configuration file"
  template:
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    src: mod_cluster.conf.j2
    dest: "{{jboss_jws_instance_dir }}/jws-3.0/httpd/conf.d/mod_cluster.conf"
    mode: "0644"

- name: "STEP 12. Create the service directory"
  file:
    path: "{{jboss_jws_instance_dir }}/jws-3.0/httpd/service"
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    state: directory
    mode: "0750"

- name: "STEP 13. Generate service systemd unit file"
  template:
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    src: jboss-jws-rhel.service.j2
    dest: "{{jboss_jws_instance_dir }}/jws-3.0/httpd/service/{{ jboss_jws_instance_service_name }}.service"
    mode: "0750"

- name: "Step 13b. set full path to httpd"
  lineinfile:
    regexp: "^HTTPD=.*"
    line: "HTTPD={{ jboss_jws_instance_dir }}/sbin/httpd"
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    dest: "{{jboss_jws_instance_dir }}/jws-3.0/httpd/sbin/apachectl"
  become: yes

- name: "Step 14. Generate JWS Apache systemd unit file"
  template:
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    src: jboss-jws-rhel.service.j2
    dest: "/etc/systemd/system/{{ jws_apache.service }}_{{ jboss_jws_instance_name }}.service"
    mode: "0755"
  register: systemd_service_file

- name: "Step 19. Update ACL"
  acl:
    name: "{{jboss_jws_instance_dir }}/jws-3.0/httpd/"
    etype: "{{ item.type }}"
    state: present
    permissions: '{{ item.permissions }}'
    default: true
    recursive: true
  become: yes
  with_items:
  - type: user
    permissions: rw-
  - type: group
    permissions: r--
  - type: other
    permissions: r--