---

- name: "Step 9. Generate httpd.conf"
  template:
    src: httpd.conf.j2
    dest: "{{ jboss_jws_home }}/httpd/conf/httpd.conf"
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
  become: true

- name: "Step 10. Remove ssl.conf"
  file:
    dest: "{{ jboss_jws_home }}/httpd/conf.d/ssl.conf"
    state: absent
  become: true

- name: "Step 11. Create mod_cluster configuration file"
  template:
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    src: mod_cluster.conf.j2
    dest: "{{ jboss_jws_home }}/httpd/conf.d/mod_cluster.conf"
    mode: "0644"

- name: "STEP 12. Create the service directory"
  file:
    path: "{{ jboss_jws_home }}/httpd/service"
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    state: directory
    mode: "0750"

- name: "STEP 13. Generate service systemd unit file"
  template:
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    src: jboss-jws-rhel.service.j2
    dest: "{{ jboss_jws_home }}/httpd/service/{{ jboss_jws_instance_service_name }}.service"
    mode: "0750"

- name: "Step 13b. set full path to httpd"
  lineinfile:
    regexp: "^HTTPD=.*"
    line: "HTTPD={{ jboss_jws_home }}/httpd/sbin/httpd"
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    dest: "{{jboss_jws_home }}/httpd/sbin/apachectl"
  become: yes

- name: "Step 13c. set JWS_HOME variable"
  lineinfile:
    insertafter: "^HTTPD=.*"
    line: "export JWS_HOME={{ jboss_jws_home }}/httpd/sbin/httpd"
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    dest: "{{jboss_jws_home }}/httpd/sbin/apachectl"
  become: yes

- name: "Step 13d. set LD_LIBRARY_PATH variable"
  lineinfile:
    insertafter: "^HTTPD=.*"
    line: "export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:{{ jboss_jws_home }}/httpd/lib\""
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    dest: "{{jboss_jws_home }}/httpd/sbin/apachectl"
  become: yes

- name: "Step 13e. set LD_LIBRARY_PATH variable"
  lineinfile:
    insertafter: "^HTTPD=.*"
    line: "export OPTIONS=\"-f {{ jboss_jws_home }}/httpd/conf/httpd.conf -E {{ jboss_jws_home }}/httpd/logs/httpd.log -d {{ jboss_jws_home }}\""
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    dest: "{{jboss_jws_home }}/httpd/sbin/apachectl"
  become: yes

- name: "Step 14. Generate JWS Apache systemd unit file"
  template:
    owner: "{{ jws_apache.user }}"
    group: "{{ jws_apache.group }}"
    src: jboss-jws-rhel.service.j2
    dest: "/etc/systemd/system/{{ jboss_jws_instance_service_name }}.service"
    mode: "0755"
  register: systemd_service_file

- name: "Step 19. Update ACL"
  acl:
    name: "{{ jboss_jws_home }}/httpd/"
    etype: "{{ item.type }}"
    state: present
    permissions: '{{ item.permissions }}'
    default: true
    recursive: true
  become: yes
  with_items:
  - type: user
    permissions: rw-
  - type: group
    permissions: r--
  - type: other
    permissions: r--