---
#- name: "{{ jboss_jws_instance_name }} (05) Run Postinstall"
#  become: yes
#  command: bash -c "cd {{ jboss_jws_check_dir }} && ./.postinstall"

#- name: "{{ jboss_jws_instance_name }} (05) Ensure JBoss EAP is running"
#  service:
#    name: "{{ jboss_jws_instance_service_name }}"
#    state: started
#    enabled: yes
